# Documentation:
# https://github.com/jacky8399/PortableBeacons/blob/master/src/main/resources/config.yml

# The configuration version. Shouldn't be modified.
config-version: 1
# Configuration related to beacon items
# Use /pb updateitems to mark preexisting items for update
# Items will be updated when they are next ticked
beacon-item:

  name: Portable Beacon # Note: players can of course rename the item in anvils
  lore:
    - '&7Shift+right click to configure potion effects'
  custom-model-data: -1 # Custom model data; Set to -1 to disable

  # Show a glowing outline around nearby beacons to players who can perform a ritual
  creation-reminder:
    enabled: true
    message: '&aYou feel that something is resonating with the beacon...' # Message in chat, set to empty string to disable
    radius: 8 # Scan radius
    disable-if-already-own-beacon-item: true # Don't remind player if they already have a beacon in their inventory

  # Enchantments to further enhance the effects of a portable beacon
  # See recipes.yml
  custom-enchantments:
    # Reduces the experience upkeep
    exp-reduction:
      enabled: true
      # {level} can be used just like in the effects section. Additionally,
      # {exp-reduction} to get experience reduction (e.g. 20%) in percentage
      # {exp-reduction|multiplier} to get experience multiplier (e.g. 80%) in percentage
      # {exp-reduction|multiplier or reduction|number} to get experience multiplier/reduction (e.g. 20% vs 0.2) in decimal
      name: '&dExperience Efficiency {level}&8 (-{exp-reduction} exp consumption)'
      reduction-per-level: 0.2 # -20% exp consumption per level
      max-level: 5
    # Retain item on death
    soulbound:
      enabled: true
      # {level} can be used just like in the effects section. Additionally,
      # {soulbound-owner} to get name of soulbound owner
      # {soulbound-owner|uuid} to get UUID of soulbound owner
      # {soulbound-owner|name|Your custom text} to change the displayed text when the owner's name cannot be found (This is usually unnecessary)
      name: '&4Soulbound {level}&8 to {soulbound-owner}'
      max-level: 5
      # whether a level will be deducted on death
      consume-level-on-death: true
      # whether item will stop working for others if it was ever soulbound to any player
      owner-usage-only: false
      # just for fun: the item cannot be dropped/moved if it contains soulbound and a negative effect!
      # (note: protection not comprehensive)
      just-for-fun-curse-of-binding: false

  # Effects Toggle GUI
  # Player must have permission portablebeacons.effects-toggle
  effects-toggle:
    enabled: true
    title: "&5Toggle Potion Effects"
    # Format: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/text/MessageFormat.html
    exp-usage-message: "&eUses 1 experience level every &6{0,number,0.##} seconds"
    # Whether the player can disable negative effects
    allow-disabling-negative-effects: false
    # Require individual permission for toggling effects (portablebeacons.effects-toggle.<effect name>)
    require-permission: false

  # Futile attempts to balance portable beacons
  nerfs:
    # Experience levels consumed per minute (set to 0 to disable)
    # upkeep per minute = value * (levels of every effect + levels of custom enchantments)
    # With the default value, the upkeep is 1 level/minute for a beacon with 6 Level III effects
    # The correct amount of experience is checked and deducted every 3.75 seconds
    exp-levels-per-minute: 0.0555555552
    # Whether the beacon should be active only when it is in the hotbar
    only-apply-in-hotbar: false
    # If true, downgrade all effects stronger than its max-amplifier (see effects.<effect-name>.max-amplifier)
    # Note: requires an item update (/pb updateitems) to take effect
    force-downgrade: false
    # Portable beacons will be disabled in these worlds
    # For finer control, use WorldGuard
    disabled-worlds:
      - disabled_world_1
      - disabled_world_2

# Specify the name and custom behavior of different potion effects
effects:
  default:
    # How long the effects will last when applied, in ticks
    duration: 280
    # The maximum amplifier allowed in recipes
    # To apply this change retroactively, see beacon-item.nerfs.force-downgrade
    max-amplifier: 3
    # Set to true to hide particles for the effect, false to use beacon ambient effect
    hide-particles: false
  regeneration:
    # How the effect is displayed in the item lore
    # Use 1.16+ RGB colors with EssentialsX format (&#RRGGBB)
    # Use {level} for Roman numeral (Regeneration III)
    # (The space before {level} is removed to avoid extra space when level = 1)
    # Use {level|number} for decimal (Regeneration 3)
    # name: '&cRegeneration {level}' will replicate default behavior
    name: '&cRegeneration'
  speed:
    name: '&fSpeed'
  resistance:
    name: '&9Resistance'
  haste:
    name: '&eHaste'
  jump_boost:
    name: '&aJump Boost'
  strength:
    name: '&4Strength'
  # You can add more potion effects, the key must match vanilla names
  # Specifying duration & max-amplifier overrides values from the default section
  # For example, to prevent the night vision effect from flickering:
  night_vision:
    name: '&1Night Vision'
    duration: 400

# Ritual to create portable beacons by dropping an item onto an active beacon
ritual:
  enabled: true
  __: ritual.item is saved by the plugin! If it is empty, the default (32x nether_star) is used
  item:

world-interactions:
  # Allow players to place down portable beacons, rebuilding the original beacon pyramid
  # (The ritual item will not be refunded)
  # Beware of dupe exploits allowing duplication of beacon base blocks!
  placement-enabled: false
  # Allow beacons to be picked up by mining when the ritual item is AIR (/pb setritualitem with empty hand)
  pickup-enabled: true
  # Require silk touch tool to pick up
  pickup-requires-silk-touch: true

# Enable WorldGuard integration
world-guard: true