# To see descriptions of different options:
# https://github.com/jacky8399/PortableBeacons/blob/master/src/main/resources/config.yml
beacon-item:
  name: Portable Beacon # Item name for portable beacon
  lore: [] # Item lore for portable beacon
  custom-model-data: -1 # Custom model data for portable beacon
  creation-reminder:
    enabled: true
    message: '&aYou feel that something is resonating with the beacon...' # Message to send to player when such reminder is active
    radius: 8 # Scan radius
    disable-if-already-own-beacon-item: true # Don't remind player if they have a portable beacon in their inventory
  custom-enchantments:
    exp-reduction:
      enabled: true
      name: '&dExperience Efficiency'
      # to disable set to empty string
      # enchantment: ''
      enchantment: mending
      # Reduction in experience consumption per enchantment level
      reduction-per-level: 0.2
      max-level: 5
    soulbound:
      enabled: true
      name: '&4Soulbound'
      enchantment: binding_curse
      max-level: 5
      # whether a level will be deducted on death
      consume-level-on-death: true
      # whether item will stop working for other players if it was soulbound to any player
      owner-usage-only: false

  nerfs: # One cycle is every 7.5s
    exp-percentage-per-cycle: 0.05555555555
    # Whether the effects should only be applied when the item is in hotbar
    only-apply-in-hotbar: false
    # Force downgrade all effects stronger than its max-amplifier
    # Note: requires an item update to take effect
    force-downgrade: false
    # Portable beacons will be disabled in these worlds
    # For finer control, use WorldGuard
    disabled-worlds:
      - disabled_world_1
      - disabled_world_2

# Specify the name and custom behavior of different potion effects
effects:
  default:
    # How long the effects will last when applied, in ticks
    duration: 280
    # The maximum amplifier allowed. Set to 0 to disallow the effect, even in commands.
    max-amplifier: 3
    # Set to true to hide particles for the effect, false to use beacon ambient effect
    hide-particles: false
  REGENERATION:
    # Display name of the effect
    # Use 1.16+ RGB colors with EssentialsX format (&#RRGGBB)
    name: '&cRegeneration'
  SPEED:
    name: '&fSpeed'
  RESISTANCE:
    name: '&9Resistance'
  HASTE:
    name: '&eHaste'
  JUMP_BOOST:
    name: '&aJump Boost'
  STRENGTH:
    name: '&4Strength'
  # You can add more potion effects, the key must match vanilla/Bukkit names
  # Specifying duration & max-amplifier overrides default section
  # For example,
# NIGHT_VISION:
#   name: '&1Night Vision'
#   duration: 400


anvil-combination:
  enabled: true # Enable combining portable beacons in anvil
  max-effects: 6 # Max no. of effects the resultant item can have
  # true for simple combination (e.g. Speed II + Speed I = Speed III)
  # false for anvil-like combination (e.g. Speed II + Speed II = Speed III)
  combine-effects-additively: true
  # enforce the vanilla repair cost limit (max. 39 levels)
  enforce-vanilla-exp-limit: true

# Enable WorldGuard integration
world-guard: true
# Item used is generated on startup